---
title: "Group_3_final_project_map"
output: html_document
---


```{r setup, include=FALSE, eval=TRUE}
knitr::opts_chunk$set(warnings=FALSE, include=FALSE, eval=TRUE)
```


```{r install_packages, eval=TRUE, cache=TRUE}

install.packages("utilsIPEA", repos = "http://cran.us.r-project.org")
install.packages("rgdal", repos = "http://cran.us.r-project.org")
install.packages("raster", repos = "http://cran.us.r-project.org")
install.packages("tmaptools", repos = "http://cran.us.r-project.org")
install.packages("mapshaper", repos = "http://cran.us.r-project.org")
install.packages("tmap", repos = "http://cran.us.r-project.org")
install.packages("leaflet", repos = "http://cran.us.r-project.org")
install.packages("RColorBrewer", repos = "http://cran.us.r-project.org")
install.packages("classint", repos = "http://cran.us.r-project.org")
install.packages("dplyr", repos = "http://cran.us.r-project.org")


```


```{r package, eval=TRUE, cache=TRUE}

install.packages("haven", repos = "http://cran.us.r-project.org")
install.packages("ggplot2", repos = "http://cran.us.r-project.org")
install.packages("foreign", repos = "http://cran.us.r-project.org")
library ("haven")
library("ggplot2")
library("foreign")

```

Bringing in data from Github

```{r data, include=TRUE}

link="https://github.com/quinhasf/pubpol-599/raw/master/ape_analysis.dta"
chw_fp <- read_dta(url(link))

link="https://github.com/ihsun-uw/Group3_Final_Project/raw/master/child_mortality.dta"
df <- read_dta(url(link))

```


Bringing in map

```{r map, include=TRUE, eval=TRUE}

zip_mozmap_SHP = "https://github.com/ihsun-uw/Group3_Final_Project/raw/master/Mozambique%20shape%20maps.zip"

```


```{r, eval=TRUE}
library(utils)
temp=tempfile()
download.file(zip_mozmap_SHP, temp)
unzip(temp)
```


```{r, eval=TRUE, include=FALSE}

#DMC - showing which tempfiles are in the directory

(maps=list.files(pattern = 'shp'))
```


```{r, eval=TRUE, results='hide', warning=FALSE, message=FALSE}
# notice the parameters use in the chunk!!

library(rgdal)
mozzipMap <- readOGR("MOZ-level_1.shp",stringsAsFactors=F) 
```



```{r plot_map, eval=TRUE, include=FALSE}

plot(mozzipMap)


```


```{r data_cleaning, eval=TRUE, include=FALSE}

str(chw_fp$province)
str(mozzipMap)
head(chw_fp$province, 10)
names(mozzipMap)
head(mozzipMap$CAPTION, 50)

str(mozzipMap$CAPTION)

#mozzipMap$CAPTION=as.numeric(mozzipMap$CAPTION)

mozzipMap

```


<!-- Generating the list of provinces and assigning a number
1: Cabo Delgado
2: Gaza
3: Inhambane
4: Manica
5: Maputo Provincia
6: Nampula
7: Niassa
8: Sofala
9: Tete
10: Zambezia
-->

```{r recoding_provinces, eval=TRUE, include=FALSE}

#SchoolData$Grade[SchoolData$Grade==5] <- "Grade Five"
chw_fp$province_num <- chw_fp$province

chw_fp$province_num[chw_fp$province=="CABO DELGADO"] <- 1
chw_fp$province_num[chw_fp$province=="GAZA"] <- 2
chw_fp$province_num[chw_fp$province=="INHAMBANE"] <- 3
chw_fp$province_num[chw_fp$province=="MANICA"] <- 4
chw_fp$province_num[chw_fp$province=="MAPUTO PROVINCIA"] <- 5
chw_fp$province_num[chw_fp$province=="NAMPULA"] <- 6
chw_fp$province_num[chw_fp$province=="NIASSA"] <- 7
chw_fp$province_num[chw_fp$province=="SOFALA"] <- 8
chw_fp$province_num[chw_fp$province=="TETE"] <- 9
chw_fp$province_num[chw_fp$province=="ZAMBEZIA"] <- 10


#str(mozzipMap$ID)
#names(mozzipMap)
#mozzipMap

#mozzipMap$province_num <- mozzipMap$ID

mozzipMap$province_num[mozzipMap$ID=="Cabo Delgado"] <- 1
mozzipMap$province_num[mozzipMap$ID=="Gaza"] <- 2
mozzipMap$province_num[mozzipMap$ID=="Inhambane"] <- 3
mozzipMap$province_num[mozzipMap$ID=="Manica"] <- 4
mozzipMap$province_num[mozzipMap$ID=="Maputo"] <- 5
mozzipMap$province_num[mozzipMap$ID=="Nampula"] <- 6
mozzipMap$province_num[mozzipMap$ID=="Niassa"] <- 7
mozzipMap$province_num[mozzipMap$ID=="Sofala"] <- 8
mozzipMap$province_num[mozzipMap$ID=="Tete"] <- 9
mozzipMap$province_num[mozzipMap$ID=="Zambezia"] <- 10
mozzipMap$province_num[mozzipMap$ID=="Maputo (city)"] <- 11

#chw_fp

df$province_num[df$provname=="Cabo Delgado"] <- 1
df$province_num[df$provname=="Gaza"] <- 2
df$province_num[df$provname=="Inhambane"] <- 3
df$province_num[df$provname=="Manica"] <- 4
df$province_num[df$provname=="Maputo Provincia"] <- 5
df$province_num[df$provname=="Nampula"] <- 6
df$province_num[df$provname=="Niassa"] <- 7
df$province_num[df$provname=="Sofala"] <- 8
df$province_num[df$provname=="Tete"] <- 9
df$province_num[df$provname=="Zambezia"] <- 10
df$province_num[df$provname=="Maputo Cidade"] <- 11

#creating new data frame with just the year 2010
df_new <- df[111:121,1:26]

#creating change in u5 mortality rate from 2000 - 2010
df_new$u5_change[df_new$province_num==1] <- 100*(df_new$U5M_COMB[df_new$province_num==1] - df$U5M_COMB[df$province_num==1 & df$year==2000])/df$U5M_COMB[df$province_num==1 & df$year==2000]
df_new$u5_change[df_new$province_num==2] <- 100*(df_new$U5M_COMB[df_new$province_num==2] - df$U5M_COMB[df$province_num==2 & df$year==2000])/df$U5M_COMB[df$province_num==2 & df$year==2000]
df_new$u5_change[df_new$province_num==3] <- 100*(df_new$U5M_COMB[df_new$province_num==3] - df$U5M_COMB[df$province_num==3 & df$year==2000])/df$U5M_COMB[df$province_num==3 & df$year==2000]
df_new$u5_change[df_new$province_num==4] <- 100*(df_new$U5M_COMB[df_new$province_num==4] - df$U5M_COMB[df$province_num==4 & df$year==2000])/df$U5M_COMB[df$province_num==4 & df$year==2000]
df_new$u5_change[df_new$province_num==5] <- 100*(df_new$U5M_COMB[df_new$province_num==5] - df$U5M_COMB[df$province_num==5 & df$year==2000])/df$U5M_COMB[df$province_num==5 & df$year==2000]
df_new$u5_change[df_new$province_num==6] <- 100*(df_new$U5M_COMB[df_new$province_num==6] - df$U5M_COMB[df$province_num==6 & df$year==2000])/df$U5M_COMB[df$province_num==6 & df$year==2000]
df_new$u5_change[df_new$province_num==7] <- 100*(df_new$U5M_COMB[df_new$province_num==7] - df$U5M_COMB[df$province_num==7 & df$year==2000])/df$U5M_COMB[df$province_num==7 & df$year==2000]
df_new$u5_change[df_new$province_num==8] <- 100*(df_new$U5M_COMB[df_new$province_num==8] - df$U5M_COMB[df$province_num==8 & df$year==2000])/df$U5M_COMB[df$province_num==8 & df$year==2000]
df_new$u5_change[df_new$province_num==9] <- 100*(df_new$U5M_COMB[df_new$province_num==9] - df$U5M_COMB[df$province_num==9 & df$year==2000])/df$U5M_COMB[df$province_num==9 & df$year==2000]
df_new$u5_change[df_new$province_num==10] <- 100*(df_new$U5M_COMB[df_new$province_num==10] - df$U5M_COMB[df$province_num==10 & df$year==2000])/df$U5M_COMB[df$province_num==10 & df$year==2000]
df_new$u5_change[df_new$province_num==11] <- 100*(df_new$U5M_COMB[df_new$province_num==11] - df$U5M_COMB[df$province_num==11 & df$year==2000])/df$U5M_COMB[df$province_num==11 & df$year==2000]


```




```{r layer_plot1, eval=TRUE, include=TRUE}

layerContrib=merge(mozzipMap,chw_fp, by.x='province_num', by.y='province_num',all.x=F)

```



```{r, evale=TRUE}
library(RColorBrewer)
colors <- brewer.pal(9, "BuGn")

```


```{r defining_var_toplot, include=TRUE}

varToPlot=layerContrib$ape_contrib

```


```{r color_plot1, include=TRUE}

library(classInt)

numberOfClasses=5
colorForScale='BuGn'
colors = brewer.pal(numberOfClasses, colorForScale)
intervals <- classIntervals(varToPlot, numberOfClasses,
                            style = "quantile",
                            dataPrecision = 1)
                           
colorPallette <- findColours(intervals, colors)

```


```{r plot_1, eval=TRUE, include=TRUE}

legendText="intervals"
shrinkLegend=1
title="Average Contribution of CHWs in Mozambique"

# first the ORIGINAL to signal missing values:
plot(mozzipMap,col='red',main=title, border="black", lwd=1) 

# now the info on contributions
plot(layerContrib, col = colorPallette,border=NA,add=T) #add

# this uses all previous information
legend('topright', 
       legend = names(attr(colorPallette, "table")), #values
       fill = attr(colorPallette, "palette"), #colors
       cex = shrinkLegend, #size 
       bty = "n", # no box
       title=legendText)
```


Creating a second map of the under 5 mortality rate

```{r layer_plot2, eval=TRUE}

layerContrib_2=merge(mozzipMap,df_new, by.x='province_num', by.y='province_num',all.x=F)

```


```{r define_var_plot2, include=TRUE, eval=TRUE}

varToPlot_2=layerContrib_2$U5M_COMB

```


```{r color_plot2, eval=TRUE, include=TRUE}

numberOfClasses=5
colorForScale='OrRd'
colors = brewer.pal(numberOfClasses, colorForScale)
intervals <- classIntervals(varToPlot_2, numberOfClasses,
                            style = "kmeans",
                            dataPrecision = 0)
                           
colorPallette <- findColours(intervals, colors)

```


```{r plot_2, eval=TRUE, include=TRUE}

legendText="intervals"
shrinkLegend=1
title="Under 5 mortality rate in Mozambique by province (2010)"

# first the ORIGINAL to signal missing values:
plot(mozzipMap,col='red',main=title, border="black", lwd=1) 

# now the info on contributions
plot(layerContrib_2, col = colorPallette,border=NA,add=T) #add

# this uses all previous information
legend('topright', 
       legend = names(attr(colorPallette, "table")), #values
       fill = attr(colorPallette, "palette"), #colors
       cex = shrinkLegend, #size 
       bty = "n", # no box
       title=legendText)
```

Generating one more set - change in u5 MR

```{r layer_plot3, eval=TRUE}

layerContrib_3=merge(mozzipMap,df_new, by.x='province_num', by.y='province_num',all.x=F)

```


```{r define_var_plot3, include=TRUE, eval=TRUE}

varToPlot_3=layerContrib_2$u5_change

```


```{r color_plot3, eval=TRUE, include=TRUE}

numberOfClasses=5
colorForScale='YlOrRd'
colors = brewer.pal(numberOfClasses, colorForScale)
intervals <- classIntervals(varToPlot_3, numberOfClasses,
                            style = "kmeans",
                            dataPrecision = 0)
                           
colorPallette <- findColours(intervals, colors)

```


```{r plot3, eval=TRUE, include=TRUE}

legendText="intervals"
shrinkLegend=1
title="Percent change in u5 mortality rate in Mozambique by province \n(2000-2010)"

# first the ORIGINAL to signal missing values:
plot(mozzipMap,col='red',main=title, border="black", lwd=1) 

# now the info on contributions
plot(layerContrib_3, col = colorPallette,border=NA,add=T) #add

# this uses all previous information
legend('topright', 
       legend = names(attr(colorPallette, "table")), #values
       fill = attr(colorPallette, "palette"), #colors
       cex = shrinkLegend, #size 
       bty = "n", # no box
       title=legendText)
```



